name: Deploy Bloomlife to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build the project
      run: bun run build

    - name: Deploy to VPS
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        SOURCE: "./"
        TARGET: ${{ secrets.SVELTE_APP_DIR }}
        ARGS: '-avz --delete'
        EXCLUDE: 'node_modules, .git, .env'

    - name: Update Port and Restart
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.SVELTE_APP_DIR }}
          export APP_PORT=${{ secrets.APP_PORT }}
          bun install --production
          pm2 reload ecosystem.config.js --env production --update-env
          pm2 save