name: Deploy SvelteKit App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install
      env:
        NODE_ENV: production

    - name: Build project
      run: bun run build
      env:
        PORT: ${{ secrets.APP_PORT }}

    # SSH Key setup and test before deploy
    - name: Setup SSH and Verify Access
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

        echo "Testing SSH connection..."
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'SSH OK'"

    - name: Deploy to VPS
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        SOURCE: "./"
        TARGET: /var/www/html/${{ secrets.APP_NAME }}
        ARGS: '-avz --delete'
        EXCLUDE: 'node_modules,.env,.git,.github,.ssh,.bashrc,.cache'

    - name: Configure and Restart Service
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm use 22

          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"

          cd /var/www/html/${{ secrets.APP_NAME }}

          bun install

          APP_PORT=${{ secrets.APP_PORT }} pm2 reload ecosystem.config.cjs --env production --update-env

          pm2 save
          pm2 list

          echo "App responded with:"
          curl -sI http://localhost:${{ secrets.APP_PORT }} || true